version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tailwindcss
    versions:
    - 2.1.2
  - dependency-name: react-markdown
    versions:
    - 6.0.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.2
    - 13.0.0
    - 13.0.1
    - 13.0.2
